#!/usr/bin/env python3
"""
Test script for Excel generation.

Run this directly to test Excel generation without the full IPC stack:
    python test_excel.py

This will generate a sample Excel file in the temp directory.
"""

import json
import sys
import os

# Add parent to path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from handlers.excel_handler import ExcelHandler


def test_basic_excel():
    """Test basic Excel generation."""
    print("Testing basic Excel generation...")
    
    handler = ExcelHandler()
    
    # Sample data matching expected format
    params = {
        "template": "basic",
        "data": {
            "title": "PressO Test Document",
            "date": "2025-12-29",
            "items": [
                {"name": "Product A", "quantity": 10, "price": 100.00},
                {"name": "Product B", "quantity": 5, "price": 250.00},
                {"name": "Service C", "quantity": 2, "price": 500.00},
            ],
            "notes": "This is a test document generated by PressO Python Engine."
        }
    }
    
    result = handler.handle_export_excel("test-001", params)
    
    print(json.dumps(result, indent=2))
    
    if result.get("success"):
        print(f"\n✓ Excel file created: {result['result']['file_path']}")
        print(f"  Size: {result['result']['file_size']} bytes")
        return True
    else:
        print(f"\n✗ Failed: {result['error']['message']}")
        return False


def test_empty_data():
    """Test Excel generation with minimal data."""
    print("\nTesting Excel with minimal data...")
    
    handler = ExcelHandler()
    
    params = {
        "template": "basic",
        "data": {
            "title": "Minimal Document"
        }
    }
    
    result = handler.handle_export_excel("test-002", params)
    
    print(json.dumps(result, indent=2))
    
    if result.get("success"):
        print(f"\n✓ Minimal Excel created: {result['result']['file_path']}")
        return True
    else:
        print(f"\n✗ Failed: {result['error']['message']}")
        return False


def test_ipc_format():
    """Test that responses match expected IPC format."""
    print("\nTesting IPC response format...")
    
    handler = ExcelHandler()
    
    params = {
        "data": {
            "title": "IPC Test",
            "items": [{"name": "Test", "quantity": 1, "price": 100}]
        }
    }
    
    result = handler.handle_export_excel("ipc-test-003", params)
    
    # Verify required fields
    assert "id" in result, "Missing 'id' field"
    assert "success" in result, "Missing 'success' field"
    assert result["id"] == "ipc-test-003", "ID mismatch"
    
    if result["success"]:
        assert "result" in result, "Missing 'result' field"
        assert "file_path" in result["result"], "Missing 'file_path'"
        assert "file_size" in result["result"], "Missing 'file_size'"
        print("✓ IPC format verified")
        return True
    else:
        print(f"✗ Generation failed: {result['error']['message']}")
        return False


if __name__ == "__main__":
    print("=" * 60)
    print("PressO Python Engine - Excel Handler Test")
    print("=" * 60)
    
    try:
        from openpyxl import __version__ as openpyxl_version
        print(f"openpyxl version: {openpyxl_version}")
    except ImportError:
        print("ERROR: openpyxl not installed!")
        print("Run: pip install openpyxl")
        sys.exit(1)
    
    print()
    
    tests = [
        test_basic_excel,
        test_empty_data,
        test_ipc_format,
    ]
    
    passed = 0
    failed = 0
    
    for test in tests:
        try:
            if test():
                passed += 1
            else:
                failed += 1
        except Exception as e:
            print(f"✗ Exception: {e}")
            import traceback
            traceback.print_exc()
            failed += 1
    
    print()
    print("=" * 60)
    print(f"Results: {passed} passed, {failed} failed")
    print("=" * 60)
    
    sys.exit(0 if failed == 0 else 1)

